### PR TITLE
Updating HM Red color

### PR DESCRIPTION
**Pull request by MiguelAxcar**
This PR intends to update HM Red color from `#d24632` to `#ff424a`

### CODE REVIEW

**Review by alwaysblank — COMMENTED** [review]
Is there a reason this isn't being updated to use a custom property?

**Comment by MiguelAxcar** [comment]
> Is there a reason this isn't being updated to use a custom property?

Well, I could not find any custom property holding colors on this repo. Do you want me to add it @alwaysblank ?

**Comment by alwaysblank** [comment]
The spec for `var()` allows you to set a default value if the custom prop doesn't exist: https://developer.mozilla.org/en-US/docs/Web/CSS/var#custom_properties_with_fallbacks_for_use_when_the_property_has_not_been_set

I'd recommend something like this:

```css
color: var( --post-history-red, #d24632 );
// Then use approach everywhere that color is needed.
```

Then we can set `--post-history-red` from the playbook (or, in theory, any other site that consume this).

**Comment by kadamwhite** [comment]
I agree with Ben, let's do this part with custom properties :+1:

**Review by kadamwhite — APPROVED** [review]

**Pull request merged**
